name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Create assets folder if it doesn't exist
      run: mkdir -p assets

    - name: Initialize database
      run: python3 application.py

    - name: Check if clientData.db exists
      id: check_db
      run: |
        if [ -f assets/clientData.db ]; then echo "::set-output name=exists::true"; else echo "::set-output name=exists::false"; fi

    - name: Run Tests
      if: steps.check_db.outputs.exists == 'true'
      run: pytest
